  name: Deploy to XSERVER

  on:
    push:
      branches: [ main ]

  jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to XSERVER
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.XSERVER_FTP_HOST }}
          username: ${{ secrets.XSERVER_FTP_USER }}
          password: ${{ secrets.XSERVER_FTP_PASS }}
          local-dir: ./
          server-dir: /cxmainte.com/public_html/tools/ai-cleaner/
