name: Deploy to Xserver

on:
  push:
    branches: [ main, cleaning-advisor-php ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Create config.php from secrets
      run: |
        cat > config.php << EOF
        <?php
        return [
            'gemini_api_key' => '${{ secrets.GEMINI_API_KEY }}',
            'amazon_associate_tag' => '${{ secrets.AMAZON_ASSOCIATE_TAG }}',
            'paapi_access_key' => '${{ secrets.AMAZON_ACCESS_KEY }}',
            'paapi_secret_key' => '${{ secrets.AMAZON_SECRET_KEY }}',
            'paapi_partner_tag' => '${{ secrets.AMAZON_ASSOCIATE_TAG }}',
            'paapi_host' => 'webservices.amazon.co.jp',
            'paapi_region' => 'us-west-2'
        ];
        EOF
    
    - name: Deploy to Xserver via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.XSERVER_FTP_HOST }}
        username: ${{ secrets.XSERVER_FTP_USER }}
        password: ${{ secrets.XSERVER_FTP_PASS }}
        server-dir: /cxmainte.com/public_html/tools/ai-cleaner/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          config.php.example
          README.md